### ISSUE TITLE
uncomment line 38

### ISSUE THREAD

**Issue by deepbiolabs** [developersdigest/Get-Started-With-Langchain-and-Pinecone-in-Node.js#2]
It looks like there is a line commented out inadvertently in main.js (at step 12)

**Comment by Bigthinz** [comment]
The updatePinecone function, handles updating the document. you can leverage the updatePinecone vector to ensure your document remains up-to-date.

**Comment by Bigthinz** [comment]
> It looks like there is a line commented out inadvertently in main.js (at step 12)

The updatePinecone function, handles updating the document. you can leverage the updatePinecone vector to ensure your document remains up-to-date.

**Comment by deepbiolabs** [comment]
OK, thank you!
